AvansK/Models/CreateFoodPackage.cs
using Core.Domain;

namespace Portal.Models;

public class CreateFoodPackage
{
    public string Name { get; set; }

    public List<Product> Products { get; set; }
}
   

AvansK/Models/ErrorViewModel.cs
namespace AvansK.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AvansK/Models/FoodPackageViewModel.cs
namespace Portal.Models;


public class FoodPackageViewModel
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int ProductId { get; set; }

    public ICollection<PackageDetailViewModel>? PackageDetails { get; set; }
}

AvansK/Models/PackageDetailViewModel.cs
namespace Portal.Models;

public class PackageDetailViewModel
{
    public int Id { get; set; }

    public int FoodPackageId { get; set; }

    public int ProductId { get; set; }

    public ProductViewModel Product { get; set; } = null!;

    public FoodPackageViewModel FoodPackage { get; set; } = null!;
}

AvansK/Models/ProductViewModel.cs
namespace Portal.Models
{
    public class ProductViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;

        public bool ContainsAlcohol { get; set; }

        public string Picture { get; set; }

    }
}

AvansK/Models/ViewModelHelper.cs
using Core.Domain;

namespace Portal.Models
{
    public static class ViewModelHelper
    {
        public static List<ProductViewModel> ToViewModel(this IEnumerable<Product> products)
        {
            var result = new List<ProductViewModel>();

            foreach (var product in products)
            {
                result.Add(product.ToViewModel());
            }

            return result;
        }

        public static List<FoodPackageViewModel> ToViewModel(this IEnumerable<FoodPackage> foodPackages)
        {
            var result = new List<FoodPackageViewModel>();

            foreach (var foodPackage in foodPackages)
            {
                result.Add(foodPackage.ToViewModel());
            }

            return result;
        }

        public static ProductViewModel ToViewModel(this Product product)
        {
            var result = new ProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                ContainsAlcohol = product.ContainsAlcohol,
                Picture = product.Picture,
            };

            return result;

        }

        public static FoodPackageViewModel ToViewModel(this FoodPackage foodPackage)
        {
            var result = new FoodPackageViewModel
            {
                Id = foodPackage.Id,
                Name = foodPackage.Name,
            };

            return result;

        }


    }
}

AvansK/Controllers/FoodPackageController.cs
using Core.Domain;
using Core.DomainServices;
using Microsoft.AspNetCore.Mvc;
using Portal.Models;

namespace Portal.Controllers
{
    public class FoodPackageController : Controller
    {
        private readonly IFoodPackageRepository _foodPackageRepository;
        private readonly IProductRepository _productRepository;

        public FoodPackageController(IFoodPackageRepository foodPackageRepository, IProductRepository productRepository)
        {
            _foodPackageRepository = foodPackageRepository;
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            PreFillFoodPackage();
            var listOfWeetIkVeel = _foodPackageRepository.GetAll();
            return View(listOfWeetIkVeel);
        }

        public IActionResult Add()
        {
            ViewBag.Products= _productRepository.GetAll();

            var products = _productRepository.GetAll();
            var viewModel = new CreateFoodPackage { Products = (List<Product>)products };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _foodPackageRepository.RemoveProduct(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> NewPackage(CreateFoodPackage package)
        {
            //var newFoodPackage = new FoodPackage(package.);

            //await _foodPackageRepository.AddPackage();
            return RedirectToAction("Index");
        }

        private void PreFillFoodPackage()
        {
            var products = _productRepository.GetAll();
            ViewBag.Products = products;

        }
    }
}

AvansK/Controllers/HomeController.cs
using AvansK.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AvansK.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AvansK/Controllers/ProductController.cs
using Core.DomainServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Portal.Models;

namespace Portal.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        // GET: ProductController
        public ActionResult Index()
        {
            return View(_productRepository.GetAll().ToViewModel());
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AvansK/Views/FoodPackage/Add.cshtml
@*@using Core.Domain;
@{
    ViewData["Title"] = "Add";
}
@model CreateFoodPackage*@

@using Core.Domain;
@using Portal.Models;

@{
    ViewData["Titel"] = "Add";
}

@model CreateFoodPackage

<h1>Add</h1>

<form asp-action="NewPackage" method="post">

    <div class="form-group">
        <label asp-for="Name">Naam</label>
        <input class="form-control" asp-for="Name" />
    </div>

    @for (int i = 0; i < Model.Products.Count; i++)
    {
        <div>
            <label>@Model.Products[i].Name</label>
            <input type="checkbox" name="SelectedProductIds" value="@Model.Products[i].Id" />
        </div>
    }

    <div class="form-group row">
        <button class="btn btn-primary col-sm-4 text-center">Add product</button>
    </div>
</form>



       }

AvansK/Views/FoodPackage/Index.cshtml
@using Core.Domain
@using Portal;
@{
    ViewData["Title"] = "Index";
}

@model List<FoodPackage>;


<h1>Food</h1>

<button class="btn btn-primary"><a style="text-decoration: none; color:white;" asp-area="" asp-controller="FoodPackage" asp-action="Add">Add</a></button>

<table class="table table-striped">
    <thead>
    <th>Id</th>
    <th>Name</th>
    <th>products</th>
    <th></th>
    </thead>
    <tbody>
        @foreach (var foodPackage in @Model)
        {
            <tr>
                <td>@foodPackage.Id</td>
                <td>@foodPackage.Name</td>
                <td>
                    @if (foodPackage.PackageDetails != null)
                    {
                        @foreach (var item in foodPackage.PackageDetails)
                        {
                            <p>@item.Product.Name</p>
                        }
                    }
                </td>
                <td>
                    <form asp-action="" asp-route-id="" method="post">
                        <button class="btn btn-danger">Delete</button>
                    </form>
                    <a class="btn btn-sm btn-primary" asp-action="" asp-route-id="">
                        Update
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

AvansK/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AvansK/Views/Product/Add.cshtml
@using Portal.Models;

@{
    ViewData["Title"] = "Add";
}
@model ProductViewModel

<h1>Add</h1>

<form asp-action="Create" method="post">

    <div class="form-group">
        <label asp-for="Name">Naam</label>
        <input class="form-control" asp-for="Name" />
    </div>

    <div class="form-group">
        <label asp-for="ContainsAlcohol">Bevat Alcohol</label>
        <input asp-for="ContainsAlcohol" />
    </div>

    <div class="form-group">
        <label asp-for="Picture">Pic</label>
        <input class="form-control" asp-for="Picture" />
    </div>

    <div class="form-group row">
        <button class="btn btn-primary col-sm-4 text-center">Add product</button>
    </div>
</form>

AvansK/Views/Product/Edit.cshtml
@using Core.Domain;
@{
    ViewData["Title"] = "Edit";
}
@model Product

<h1>Edit</h1>

<form asp-action="Edit" method="post" asp-route-id="@Model.Id">

    <div class="form-group">
        <label asp-for="Name">Naam</label>
        <input class="form-control" asp-for="Name" value="@Model.Name" />
    </div>

    <div class="form-group">
        <label asp-for="ContainsAlcohol">Bevat Alcohol</label>
        <input asp-for="ContainsAlcohol" value="@Model.ContainsAlcohol" />
    </div>

    <div class="form-group">
        <label asp-for="Picture">Pic</label>
        <input class="form-control" asp-for="Picture" value="@Model.Picture" />
    </div>

    <div class="form-group row">
        <button class="btn btn-primary col-sm-4 text-center">Edit product</button>
    </div>
</form>

AvansK/Views/Product/Index.cshtml
@using Portal.Models;
@{
    ViewData["Title"] = "Index";
}

@model List<ProductViewModel>

<h1>Product</h1>

<button class="btn btn-primary"><a style="text-decoration: none; color:white;" asp-area="" asp-controller="Product" asp-action="Add">Add</a></button>

<table class="table table-striped">
    <thead>
    <th>Id</th>
    <th>Name</th>
    <th>ContainsAlcohol</th>
    <th>Pic</th>
    <th></th>
    </thead>
    <tbody>
        @foreach (var product in @Model)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.ContainsAlcohol</td>
                <td>@product.Picture</td>
                <td>
                    <form asp-action="RemoveProduct" asp-route-id="@product.Id" method="post">
                        <button class="btn btn-danger">Delete</button>
                    </form>
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@product.Id">
                        Update
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

AvansK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvansK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AvansK.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AvansK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FoodPackage" asp-action="Index">Food</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AvansK - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>